---
docker:
  buildkit: true
  from: perl:5.32.1
  image: tekki/mojolicious

git:
  repo: https://github.com/Tekki/docker-mojolicious

global:
  app_folder: /usr/src/app
  debian_packages:
    - software-properties-common
    - dirmngr
  description: >
    [Mojolicious](https://mojolicious.org) is a real-time web framework and web development toolkit
    written in [Perl](https://www.perl.org).
  license: Artistic-2.0
  mojo_version: 8.72
  perl_modules:
    - Cpanel::JSON::XS
    - DBI
    - EV
    - Future::AsyncAwait
    - IO::Socket::Socks
    - Net::SSLeay
    - IO::Socket::SSL
    - Net::DNS::Native
    - Role::Tiny
    - SQL::Abstract
  title: Mojolicious

releases:
  main:
    versions:
      - 8.72
      - 8
      - latest
  mariadb:
    env:
      DBD_MYSQL_CONFIG: mariadb_config
    keys:
      - 177F4010FE56CA3336300305F1656F24C74CD1D8
      - 430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A
      - 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    packages:
      - libmariadb-dev
    perl_modules:
      - DBD::MariaDB
      - DBD::mysql
      - Mojo::mysql
    repos:
      - deb http://ftp.osuosl.org/pub/mariadb/repo/10.3/debian stretch main
    versions:
      - 8.72-mariadb
      - 8-mariadb
      - mariadb
  mysql:
    keys:
      - A4A9406876FCBD3C456770C88C718D3B5072E1F5
    packages:
      - libmysqlclient-dev
    perl_modules:
      - DBD::MariaDB
      - DBD::mysql
      - Mojo::mysql
    repos:
      - deb http://repo.mysql.com/apt/debian/ stretch mysql-8.0
    versions:
      - 8.72-mysql
      - 8-mysql
      - mysql
  pg:
    keys:
      - B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    packages:
      - libpq-dev
    perl_modules:
      - DBD::Pg
      - Mojo::Pg
    repos:
      - deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
    versions:
      - 8.72-pg
      - 8-pg
      - pg
  sqlite:
    perl_modules:
      - DBD::SQLite
      - Mojo::SQLite
    versions:
      - 8.72-sqlite
      - 8-sqlite
      - sqlite

templates:
  - source: dockerfile.ep
    target: Dockerfile
